//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Visitora.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.Visits = new HashSet<Visit>();
        }
    
        public int Id { get; set; }
        public string name { get; set; }
        public Nullable<int> State_Id { get; set; }
        public string status { get; set; }
        public double latitude { get; set; }
        public double longitude { get; set; }
    
        public virtual State State { get; set; }
        public virtual ICollection<Visit> Visits { get; set; }
    }
}
